### ISSUE TITLE
Wrong fiat price for ysteCRV

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe-transaction-service#302]
**Describe the bug**

Wrong fiat price for ysteCRV

**To Reproduce**
1. Open https://gnosis-safe.io/app/#/safes/0x3217b819ea2d25f1982bae5dd9c8fe4c6d546bfc/balances 
2. Check the price of ysteCRV
![image](https://user-images.githubusercontent.com/1380529/124620413-b8eed100-de79-11eb-89ab-b95a6a7925f0.png)

**Expected behavior**
1. Open https://app.zerion.io/0x3217b819ea2d25f1982bae5dd9c8fe4c6d546bfc/overview
2. Check the price of ysteCRV
![image](https://user-images.githubusercontent.com/1380529/124620524-d02dbe80-de79-11eb-87cf-187932415d12.png)

**Additional context**
It seems like the returned value is in ETH rather than USD. Could that be?

**Comment by Uxio0** [comment]
Hi @tschubotz , it looks good to me. Prices for yearn _yVaults_ are calculated calling `pricePerShare` on the smart contract, dividing by `1e18` and multiplying for the balance of the user. What do you think?

https://etherscan.io/address/0xdCD90C7f6324cfa40d7169ef80b12031770B4325#readContract

**Comment by tschubotz** [comment]
Hmm, then this way of calculating is wrong 😅 

415 ysteCRV are not worth only 400USD but rather ~1M USD :) 

Another source: https://zapper.fi/dashboard?address=0x3217b819ea2d25f1982bae5dd9c8fe4c6d546bfc -> yearn

Now that I'm thinking about it, the price of the YFI yVault is also wrong. 🤔 
![image](https://user-images.githubusercontent.com/1380529/124732037-197e1c80-df13-11eb-9828-7be1f8ee2a16.png)


Checking the Safe from the [other ticket](https://github.com/gnosis/safe-transaction-service/issues/288), it seem like there are still discrepancies between our prices and Zerion 🤔 

- https://app.zerion.io/0xFEB4acf3df3cDEA7399794D0869ef76A6EfAff52/overview
- https://gnosis-safe.io/app/#/safes/0xFEB4acf3df3cDEA7399794D0869ef76A6EfAff52/balances

I'll check this out in more detail later this week to see if I can find the reason :)

**Comment by Uxio0** [comment]
Oh, then I have no clue of how to get the price. When I implemented this I checked some yVaults and prices were the same, maybe contract price is not updated anymore.

**Comment by Uxio0** [comment]
I got it wrong @tschubotz https://docs.yearn.finance/developers/v1-yvaults-documentation/v1-yvault-interfaces#function-getpriceperfullshare

I will test it with the new logic

**Comment by tschubotz** [comment]
Many yearn and curve tokens looks perfect now!

Something is still wrong with those prices those 🙈 

- Seems we don't have any fiat price for the steCRV yVault: https://gnosis-safe.io/app/#/safes/0x3217b819ea2d25f1982bae5dd9c8fe4c6d546bfc/balances
- For the underlying steCRV, we seem to have a wrong fiat price, differing from Zerion and other price sources I have checked: https://gnosis-safe.io/app/#/safes/0x9817569dc3015c84846159dabcb80425186f506f/balances

Reopening just to keep track of it, probably not highest prio to fix this, comared to the L2 topics.

**Comment by Uxio0** [comment]
ddc7ecbefcede7d968ea7ffa9b9b7dff1a39bf5f should fix it
