### ISSUE TITLE
Can't read etags headers from the frontend

### ISSUE THREAD

**Issue by Agupane** [gnosis/safe-transaction-service#73]
We need that the backend supports `Access-Control-Expose-Headers` for etags in order to read that value within the frontend

More information about this can be read [here](https://stackoverflow.com/questions/37897523/axios-get-access-to-response-header-fields)

**Comment by Uxio0** [comment]
This issue has been fixed, can you test it @Agupane?

**Comment by Agupane** [comment]
Hi @Uxio0 ! I'm afraid that the issue is still there. This is the url example that I'm using:
```
https://safe-transaction.staging.gnosisdev.com/api/v1/safes/0xdfA693da0D16F5E7E78FdCBeDe8FC6eBEa44f1Cf/transactions/
```

And this are the response headers:
![image](https://user-images.githubusercontent.com/21086218/76219695-fa735b80-61f4-11ea-871d-b1f6c88cd002.png)

**Comment by Uxio0** [comment]
Can you try again? :)

**Comment by Agupane** [comment]
It's still the same :(

**Comment by Uxio0** [comment]
> Hi @Uxio0 ! I'm afraid that the issue is still there. This is the url example that I'm using:
> 
> ```
> https://safe-transaction.staging.gnosisdev.com/api/v1/safes/0xdfA693da0D16F5E7E78FdCBeDe8FC6eBEa44f1Cf/transactions/
> ```

It should be working now, I see this when querying that url, so it seems ok backend side:

```
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization
Access-Control-Allow-Methods: OPTIONS, GET, HEAD
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: etag
```

**Comment by Agupane** [comment]
It's working now, maybe there was a problem with cache?.

Closing this issue, thanks for you help :)

**Comment by Uxio0** [comment]
Awesome :) Thanks @Agupane
